[author]
name = "fristonio"
email = "contact+fristonio@sdslabs.co.in"
ssh_key = "ssh-rsa AAAAB3NzaC1y"

[challenge.metadata]
name = "xinetd-service"
flag = "CTF{sample_flag}"
type = "service"
hints = ["xinetd_hint_1", "xinetd_hint_2"]

[challenge.env]
apt_deps = ["gcc", "socat"]
setup_scripts = ["setup.sh"]
service_path = "pwn"
ports = [10003]
